[ci] Invoke failure if any of build jobs failed (#70)
#64

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -135,3 +135,16 @@ jobs:
         uses: ./.github/workflows/ci-cmake
         with:
           preset: ${{ matrix.preset }}
+
+  check-success:
+    runs-on: ubuntu-latest
+    needs: [windows-build, linux-build, macos-build]
+    steps:
+      - name: check success
+        run: |
+          if [[ "${{ needs.windows-build.result }}" != "success" ]] || \
+             [[ "${{ needs.linux-build.result }}" != "success" ]] || \
+             [[ "${{ needs.macos-build.result }}" != "success" ]]; then
+            echo "One or more builds failed."
+            exit 1
+          fi
